In [1]:
import pandas as pd
import numpy as np
from pyECLAT import ECLAT

In [3]:
base_mercado1 = pd.read_csv('D:/cursos/curso-machine-learning/bases_dados/mercado.csv', header=None)
base_mercado1

          0        1         2         3
0     leite  cerveja       pao  manteiga
1      cafe      pao  manteiga       NaN
2      cafe      pao  manteiga       NaN
3     leite     cafe       pao  manteiga
4   cerveja      NaN       NaN       NaN
5  manteiga      NaN       NaN       NaN
6       pao      NaN       NaN       NaN
7    feijao      NaN       NaN       NaN
8     arroz   feijao       NaN       NaN
9     arroz      NaN       NaN       NaN

In [4]:
eclat = ECLAT(data=base_mercado1)

In [5]:
eclat.df_bin

   leite  cerveja  cafe  arroz  pao  manteiga  feijao
0      1        1     0      0    1         1       0
1      0        0     1      0    1         1       0
2      0        0     1      0    1         1       0
3      1        0     1      0    1         1       0
4      0        1     0      0    0         0       0
5      0        0     0      0    0         1       0
6      0        0     0      0    1         0       0
7      0        0     0      0    0         0       1
8      0        0     0      1    0         0       1
9      0        0     0      1    0         0       0

In [6]:
eclat.uniq_

['leite', 'cerveja', nan, 'cafe', 'arroz', 'pao', 'manteiga', 'feijao']

In [7]:
indices, suporte = eclat.fit(min_support=0.3, min_combination=1, max_combination=3)

Combination 1 by 1

3it [00:00, 222.05it/s]

Combination 2 by 2

3it [00:00, 286.56it/s]

Combination 3 by 3

1it [00:00, 256.78it/s]

In [8]:
indices

{'cafe': [1, 2, 3],
 'pao': [0, 1, 2, 3, 6],
 'manteiga': [0, 1, 2, 3, 5],
 'cafe & pao': [1, 2, 3],
 'cafe & manteiga': [1, 2, 3],
 'pao & manteiga': [0, 1, 2, 3],
 'cafe & pao & manteiga': [1, 2, 3]}

In [9]:
suporte

{'cafe': 0.3,
 'pao': 0.5,
 'manteiga': 0.5,
 'cafe & pao': 0.3,
 'cafe & manteiga': 0.3,
 'pao & manteiga': 0.4,
 'cafe & pao & manteiga': 0.3}